In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from natsort import natsorted
from natsort import index_natsorted
from matplotlib.patches import Patch
from Bio import SeqIO

In [35]:
top_n_sequence=10
animals=["degu","dog","guineaPig","human","mouse","nmr","rat"]

In [36]:
repeat_df.columns

Index(['sequence', 'start', 'end', 'period_size', 'copies_aligned',
       'consensus_size', 'match_percent', 'indel_percent', 'alignment_score',
       'percent_A', 'percent_C', 'percent_G', 'percent_T', 'entropy',
       'repeat_sequence', 'consensus_sequence', 'seq_length', 'sequence_orig',
       'length', 'chromosome'],
      dtype='object')

In [37]:
species="degu"
check_repeat_df=pd.read_csv("repeat_df_"+str(species)+".tsv", sep='\t')
check_repeat_df["length"]=check_repeat_df["end"]-check_repeat_df["start"]
## Create chromosome column
check_repeat_df['chromosome'] = check_repeat_df['sequence'].apply(
    lambda x: 'seq_additional' if str(x).lower().startswith('seq') else x
)


check_repeat_df= check_repeat_df.sort_values(by="length", ascending=False).head(top_n_sequence)

check_repeat_df.head()

,sequence,start,end,period_size,copies_aligned,consensus_size,match_percent,indel_percent,alignment_score,percent_A,percent_C,percent_G,percent_T,entropy,consensus_sequence,repeat_sequence,seq_length,length,chromosome
905956,chr4,124515705,133203634,349,24874.5,349,90.0,2.0,11539623.0,27.0,23.0,20.0,28.0,1.99,TTCCGCGCTGTGAAAAGAGTGGCAAATCATTCAGTCTCCTAAGAGA...,TTCCGCGCTGTAAAAAGAGTGGCAAATCATTCAGTCTCCTAAGAGA...,151562733,8687929,chr4
1205517,chr17,38512437,44969366,349,18494.2,349,93.0,1.0,10381185.0,27.0,23.0,20.0,28.0,1.99,AAAACAGTGGCAAATCATTCAGTCTCCTAAGAGAAAGCATCCGTGA...,AAAAGAGTGGCAAATCATTCAGTCTCCTAAGAAAAAGCATCCGTGA...,104132507,6456929,chr17
808815,chr12,461490,6779676,348,18077.8,348,86.0,5.0,6859731.0,28.0,21.0,23.0,27.0,1.99,ACAAGCAGCTCTCTCAGGGCACTGGATTCTAGAAACGTGTTTGTGG...,ACAAGCAGCTCTCTCAGGGCACTGGATTCTAGAAAGTTGTTTGTGC...,123474991,6318186,chr12
29587,chr7,60772784,66783903,349,17169.1,349,88.0,4.0,6926539.0,27.0,23.0,20.0,28.0,1.99,TGTGTTTCTAAGTGTGAGTTCTTAATGCAGAAGAGCCAGCTAAGCT...,TGTGTTTCTAAGTGTGAGTTCTTAATGCAGAAGTGCCAACTAAGCT...,138367390,6011119,chr7
437077,chr1,176715624,181772971,349,14468.3,349,93.0,2.0,7244517.0,28.0,20.0,23.0,27.0,1.99,AGAACTCACACTTAGAAACACAAATCATGCAGTAGAAACAAGCAGC...,AGAACTCACACTTAGAAACACAAATCATGCAGTAGAAACAAGCAGC...,185300982,5057347,chr1

In [38]:
count_row=0
for species in animals:
    print("Processing: "+str(species))
    repeat_df=pd.read_csv("repeat_df_"+str(species)+".tsv", sep='\t')
    repeat_df["length"]=repeat_df["end"]-repeat_df["start"]
    ## Create chromosome column
    repeat_df['chromosome'] = repeat_df['sequence'].apply(
        lambda x: 'seq_additional' if str(x).lower().startswith('seq') else x
    )
    

    repeat_int= repeat_df.sort_values(by="length", ascending=False).head(top_n_sequence)
    repeat_int["index"]= repeat_int.index
    new_df = pd.DataFrame({
        'repeat_sequence': repeat_int['consensus_sequence'],
        'sequence_start_end_type': repeat_int['sequence'] + '_' + repeat_int['start'].astype(str) + '_' + repeat_int['end'].astype(str) + "_" + repeat_int['period_size'].astype(str)  + "_" + species +"_"+ repeat_int['index'].astype(str)
    })
    with open("animal_"+species+"_"+str(top_n_sequence)+"Longest_consensusSeq.fasta", "w") as f:
        for idx, row in new_df.iterrows():
            f.write(f">{row['sequence_start_end_type']}\n")
            f.write(f"{row['repeat_sequence']}\n")

Processing: degu
Processing: dog
Processing: guineaPig
Processing: human
Processing: mouse
Processing: nmr
Processing: rat

In [39]:
new_df

,repeat_sequence,sequence_start_end_type
584078,ATTCAGTTAGTTCCCAATAGGTCGCATAGTAATAAGTGGTTGTTCA...,chr6_2969119_5673346_185_rat_584078
1325079,GGAACGGAATCTAAGTATCATGGTGAATTGAGTAGGTTCCCAATAG...,chr17_44297223_46967036_370_rat_1325079
1325080,GAATCTAAGTAACATGGTGAATTGAGTAGGTTCCCAATAGGCCGCA...,chr17_44297414_46965655_185_rat_1325080
966264,CATGGTGAATTCAGTAGGTTCCCAATAGGATTCGCATGTAATAAGG...,chr11_8581565_11133345_185_rat_966264
584079,ATTCGGTTAGTTCCCAATAGGCCGCAGTAGTAATAAGTGGACTGTT...,chr6_2969119_5261223_370_rat_584079
1325083,ATTTTAACGAACGGAATCTAAGTATCATGGTGAATTCAGTAGTTCC...,chr17_44537064_46620367_92_rat_1325083
1155095,GAATTCAGTGAGTTCCCAATGGGACATGCTTGTAATAAGTTTGCTT...,chr14_48338786_50272549_92_rat_1155095
966279,AAAGATTTATAAAAATTTGGTGAGCCGAATCTGAGTAACATGGTGA...,chr11_9207583_11133362_370_rat_966279
966285,GAATCTAAGTAACATGGTGAATTGAGTAGGTTCCCAATAGGCCGCA...,chr11_11133543_13030924_185_rat_966285
1373706,TTCAGTTCCTTAAAATGTTGCTCTATCTTGAAAACAAGCTTATTAC...,chr18_37632889_39503519_92_rat_1373706